<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Ranium\SeedOnce\Traits\SeedOnce;

class User_role extends Seeder
{
    use SeedOnce;
    
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user_role = [
            ['designation_id' => 1,'menu_id' => 1],
            ['designation_id' => 1,'menu_id' => 2],
            ['designation_id' => 1,'menu_id' => 3],
            ['designation_id' => 1,'menu_id' => 4],
            ['designation_id' => 1,'menu_id' => 5],
            ['designation_id' => 1,'menu_id' => 6],
            ['designation_id' => 1,'menu_id' => 7],
            ['designation_id' => 1,'menu_id' => 8],
            ['designation_id' => 1,'menu_id' => 9],
            ['designation_id' => 1,'menu_id' => 10],
            ['designation_id' => 1,'menu_id' => 11],
            ['designation_id' => 1,'menu_id' => 12],
            ['designation_id' => 1,'menu_id' => 13],
            ['designation_id' => 1,'menu_id' => 14],
            ['designation_id' => 1,'menu_id' => 15],
            ['designation_id' => 1,'menu_id' => 16],
            ['designation_id' => 1,'menu_id' => 17],
            ['designation_id' => 1,'menu_id' => 18],
            ['designation_id' => 1,'menu_id' => 19],
            ['designation_id' => 1,'menu_id' => 20],
            ['designation_id' => 1,'menu_id' => 21],
            ['designation_id' => 1,'menu_id' => 22],
            ['designation_id' => 1,'menu_id' => 23],
            ['designation_id' => 1,'menu_id' => 24],
            ['designation_id' => 1,'menu_id' => 25],
            ['designation_id' => 1,'menu_id' => 26],
            ['designation_id' => 1,'menu_id' => 27],
            ['designation_id' => 1,'menu_id' => 28],
            ['designation_id' => 1,'menu_id' => 29],
            ['designation_id' => 1,'menu_id' => 30],
            ['designation_id' => 1,'menu_id' => 31],
            ['designation_id' => 1,'menu_id' => 32],
            ['designation_id' => 1,'menu_id' => 33],
            ['designation_id' => 1,'menu_id' => 34],
            ['designation_id' => 1,'menu_id' => 35],
            ['designation_id' => 1,'menu_id' => 36],
            ['designation_id' => 1,'menu_id' => 37],
            ['designation_id' => 1,'menu_id' => 38],
            ['designation_id' => 1,'menu_id' => 39],
            ['designation_id' => 1,'menu_id' => 42],
            ['designation_id' => 1,'menu_id' => 43],
			['designation_id' => 2,'menu_id' => 1],
            ['designation_id' => 2,'menu_id' => 2],
            ['designation_id' => 2,'menu_id' => 4],
            ['designation_id' => 2,'menu_id' => 5],
            ['designation_id' => 2,'menu_id' => 6],
            ['designation_id' => 2,'menu_id' => 7],
            ['designation_id' => 2,'menu_id' => 9],
            ['designation_id' => 2,'menu_id' => 10],
            ['designation_id' => 2,'menu_id' => 12],
            ['designation_id' => 2,'menu_id' => 13],
            ['designation_id' => 2,'menu_id' => 15],
            ['designation_id' => 2,'menu_id' => 16],
            ['designation_id' => 2,'menu_id' => 18],
            ['designation_id' => 2,'menu_id' => 19],
            ['designation_id' => 2,'menu_id' => 20],
            ['designation_id' => 2,'menu_id' => 21],
            ['designation_id' => 2,'menu_id' => 22],
            ['designation_id' => 2,'menu_id' => 23],
            ['designation_id' => 2,'menu_id' => 24],
            ['designation_id' => 2,'menu_id' => 25],
            ['designation_id' => 2,'menu_id' => 27],
            ['designation_id' => 2,'menu_id' => 28],
			['designation_id' => 3,'menu_id' => 1],
            ['designation_id' => 3,'menu_id' => 2],
            ['designation_id' => 3,'menu_id' => 4],
            ['designation_id' => 3,'menu_id' => 5],
            ['designation_id' => 3,'menu_id' => 6],
            ['designation_id' => 3,'menu_id' => 7],
            ['designation_id' => 3,'menu_id' => 9],
            ['designation_id' => 3,'menu_id' => 10],
            ['designation_id' => 3,'menu_id' => 12],
            ['designation_id' => 3,'menu_id' => 13],
            ['designation_id' => 3,'menu_id' => 15],
            ['designation_id' => 3,'menu_id' => 16],
            ['designation_id' => 3,'menu_id' => 18],
            ['designation_id' => 3,'menu_id' => 19],
            ['designation_id' => 3,'menu_id' => 20],
            ['designation_id' => 3,'menu_id' => 21],
            ['designation_id' => 3,'menu_id' => 22],
            ['designation_id' => 3,'menu_id' => 23],
            ['designation_id' => 3,'menu_id' => 24],
            ['designation_id' => 3,'menu_id' => 25],
            ['designation_id' => 3,'menu_id' => 27],
            ['designation_id' => 3,'menu_id' => 28],
            ['designation_id' => 4,'menu_id' => 1],
            ['designation_id' => 4,'menu_id' => 6],
            ['designation_id' => 4,'menu_id' => 7],
            ['designation_id' => 4,'menu_id' => 8],
            ['designation_id' => 4,'menu_id' => 9],
            ['designation_id' => 4,'menu_id' => 10],
            ['designation_id' => 4,'menu_id' => 11],
            ['designation_id' => 4,'menu_id' => 12],
            ['designation_id' => 4,'menu_id' => 13],
            ['designation_id' => 4,'menu_id' => 14],
            ['designation_id' => 4,'menu_id' => 15],
            ['designation_id' => 4,'menu_id' => 25],
            ['designation_id' => 4,'menu_id' => 26],
            ['designation_id' => 4,'menu_id' => 27],
            ['designation_id' => 4,'menu_id' => 29],
            ['designation_id' => 4,'menu_id' => 30],
            ['designation_id' => 4,'menu_id' => 31],
            ['designation_id' => 4,'menu_id' => 32],
            ['designation_id' => 4,'menu_id' => 33],
            ['designation_id' => 4,'menu_id' => 34],
            ['designation_id' => 4,'menu_id' => 35],
            ['designation_id' => 1,'menu_id' => 39],
            ['designation_id' => 1,'menu_id' => 40],
            ['designation_id' => 3,'menu_id' => 40],
            ['designation_id' => 1,'menu_id' => 41],
            ['designation_id' => 1,'menu_id' => 42],
            ['designation_id' => 1,'menu_id' => 43],
            ['designation_id' => 1,'menu_id' => 44],
            ['designation_id' => 1,'menu_id' => 45],
            ['designation_id' => 1,'menu_id' => 46],
            ['designation_id' => 1,'menu_id' => 47],
            ['designation_id' => 1,'menu_id' => 48],
            ['designation_id' => 1,'menu_id' => 49]
		 ];
		\App\Models\User_role::insert($user_role);
    }
}
